listeners.tcp.default = 5672
management.tcp.port = 15672
management.path_prefix = /rabbitmq
prometheus.tcp.port = 15692
loopback_users.guest = false
default_vhost = /
disk_free_limit.relative = 1.5
log.console = true
log.console.level = info
log.file = false

